import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  ShieldAlert, Sparkles, Award, Play, Info, Flame, 
  HelpCircle, ChevronRight, Scale, CheckCircle
} from 'lucide-react';

// Import local synthesized assets generated by the system builder
import heroBackground from './assets/images/hero_bg_1781877882308.jpg';
import blueWolfChips from './assets/images/wolf_chips_1781877906463.jpg';
import slotScreenPreview from './assets/images/slot_screen_1781877929811.jpg';

// Import subcomponents
import AudioEngine from './components/AudioEngine';
import SlotEmulator from './components/SlotEmulator';
import { 
  NavBar, BonusOffers, GameOverview, Features, Paytable, 
  GameplayGuide, PaymentSlider, FAQ, REDIRECT_URL, playNow 
} from './components/PageSections';

export default function App() {
  const [isLoading, setIsLoading] = useState(true);
  const [loadPct, setLoadPct] = useState(0);
  const [mode, setMode] = useState<'demo' | 'real'>('demo');

  // Simulated Loader Progress Loop (1.8 seconds)
  useEffect(() => {
    const totalTime = 1800; // 1.8 seconds
    const intervalTime = 30;
    const step = 100 / (totalTime / intervalTime);

    const timer = setInterval(() => {
      setLoadPct((prev) => {
        if (prev >= 100) {
          clearInterval(timer);
          // Small safety delay before starting fade
          setTimeout(() => setIsLoading(false), 200);
          return 100;
        }
        return Math.min(prev + step, 100);
      });
    }, intervalTime);

    return () => clearInterval(timer);
  }, []);

  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      const yOffset = -80; // offset fixed header
      const y = element.getBoundingClientRect().top + window.scrollY + yOffset;
      window.scrollTo({ top: y, behavior: 'smooth' });
    }
  };

  return (
    <div id="landing-root" className="min-h-screen bg-casino-radial text-gray-100 font-sans selection:bg-emerald-500 selection:text-black antialiased overflow-x-hidden">
      
      {/* ========================================================================
         CINEMATIC ANIMATED LOADING SCREEN
         ======================================================================== */}
      <AnimatePresence>
        {isLoading && (
          <motion.div
            id="casino-loading-overlay"
            initial={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.6 }}
            className="fixed inset-0 bg-zinc-950 z-50 flex flex-col items-center justify-center p-6 select-none"
          >
            <div className="flex flex-col items-center max-w-sm text-center">
              {/* Spinning Golden Wolf Core Coin */}
              <motion.div 
                className="w-24 h-24 rounded-full bg-gradient-to-tr from-yellow-600 via-amber-400 to-yellow-600 p-1 shadow-[0_0_40px_rgba(245,158,11,0.4)] flex items-center justify-center mb-6 border-2 border-black"
                animate={{ rotateY: 360 }}
                transition={{ repeat: Infinity, duration: 2.2, ease: "linear" }}
              >
                <div className="w-full h-full bg-black rounded-full flex items-center justify-center">
                  <span className="text-4xl">🐺</span>
                </div>
              </motion.div>

              {/* Loader Header */}
              <h2 className="text-3xl font-serif font-black tracking-widest text-white leading-none">
                WOLF TREASURE
              </h2>
              <span className="text-xs tracking-widest text-emerald-400 font-bold uppercase mt-2 block font-sans">
                POLISHING DELUXE CASINO
              </span>

              {/* Progress Bar Container */}
              <div className="w-64 h-1.5 bg-zinc-800 rounded-full mt-8 overflow-hidden border border-zinc-900 shadow-inner">
                <motion.div 
                  className="h-full bg-gradient-to-r from-emerald-500 to-green-400 shadow-[0_0_10px_#10b981]"
                  style={{ width: `${loadPct}%` }}
                />
              </div>

              {/* Loading Status Indicator */}
              <span className="text-[10px] uppercase font-mono tracking-widest text-zinc-500 mt-3 font-semibold">
                RNG Security Checked | Loading Assets {Math.floor(loadPct)}%
              </span>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* ========================================================================
         MAIN IMMERSIVE LAYOUT
         ======================================================================== */}
      {!isLoading && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.8 }}
          className="relative min-h-screen flex flex-col justify-between"
        >
          {/* Audio Synthesizer Control */}
          <AudioEngine />
          
          {/* Header Navigation */}
          <NavBar />

          {/* ====================================================================
             HERO SECTION with Parallax Landscape Background
             ==================================================================== */}
          <header 
            id="hero-header-parallax" 
            className="relative min-h-[92vh] md:min-h-screen flex items-center justify-center overflow-hidden bg-cover bg-center pt-28 pb-16 px-4"
            style={{ 
              backgroundImage: `linear-gradient(to top, #000000 0%, rgba(0,0,0,0.72) 40%, rgba(0,0,0,0.5) 100%), url(${heroBackground})` 
            }}
          >
            {/* Soft Ambient Desert Glow filter */}
            <div className="absolute inset-0 bg-radial-at-t from-emerald-900/10 via-transparent to-transparent z-0 pointer-events-none"></div>

            <div className="max-w-7xl mx-auto w-full relative z-10 flex flex-col items-center text-center">
              
              <motion.div
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8 }}
                className="mb-3 px-3 py-1.5 bg-yellow-500/10 border border-yellow-500/20 text-yellow-400 text-[10px] md:text-xs font-mono font-extrabold uppercase tracking-widest rounded-full flex items-center gap-2 shadow-inner"
              >
                <span className="w-2 h-2 rounded-full bg-emerald-500 animate-ping"></span>
                Official Slot Guide & Bonuses | 96.01% RTP Verified
              </motion.div>

              {/* Large Animated Title */}
              <motion.h1
                initial={{ scale: 0.88, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                transition={{ duration: 0.9, type: 'spring' }}
                className="text-5xl md:text-7xl lg:text-8xl font-serif font-black tracking-tighter text-white leading-[0.95] flex flex-col uppercase uppercase-accent drop-shadow-[0_4px_12px_rgba(0,0,0,0.9)]"
              >
                <span className="gold-metallic-title">Wolf Treasure</span>
                <span className="text-gold-glowing tracking-widest text-4xl md:text-5xl lg:text-6xl text-shadow-glow">Pokie Online</span>
              </motion.h1>

              <motion.p
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.8, delay: 0.3 }}
                className="text-gray-300 font-sans tracking-widest uppercase text-[11px] md:text-sm mt-5 leading-normal max-w-xl text-shadow font-semibold"
              >
                Epic Desert Night Experience. Spin stacks of howling wilds, 3x3 giant multipliers, and win three legendary Jackpot tiers!
              </motion.p>

              {/* Action Buttons with Particle Glowing Ring */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, delay: 0.5 }}
                className="mt-8 flex flex-col sm:flex-row items-center gap-4 w-full justify-center max-w-md px-4"
              >
                {/* Play Now (PRIMARY CTA) */}
                <button
                  onClick={playNow}
                  className="w-full sm:w-auto px-10 py-4.5 bg-gradient-to-r from-[#00ff00] to-[#008000] text-black font-black uppercase tracking-widest rounded-full transition-all duration-300 shadow-[0_0_25px_rgba(0,255,0,0.5)] hover:shadow-[0_0_40px_rgba(0,255,0,0.85)] hover:scale-105 cursor-pointer flex items-center justify-center gap-2.5 text-sm"
                  id="hero-play-now-cta"
                >
                  <Play className="w-4 h-4 fill-black text-black" />
                  Play For Real Funds
                </button>

                {/* Learn / Play Demo (SECONDARY CTA) */}
                <button
                  onClick={() => scrollToSection('section-emulator')}
                  className="w-full sm:w-auto px-8 py-4.5 bg-zinc-950/80 backdrop-blur-sm border border-zinc-800 hover:border-yellow-500/40 text-gray-200 hover:text-white hover:bg-zinc-900 font-extrabold uppercase tracking-widest rounded-full transition-all duration-300 hover:scale-105 cursor-pointer flex items-center justify-center gap-2 text-xs"
                  id="hero-demo-trigger"
                >
                  <Sparkles className="w-4 h-4 text-yellow-400 animate-spin-slow" />
                  Spin Play (Free Demo)
                </button>
              </motion.div>

              {/* Mini Indicators */}
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.8, delay: 0.7 }}
                className="mt-14 grid grid-cols-3 gap-6 max-w-lg w-full text-center py-4 border-t border-zinc-800/60"
              >
                <div>
                  <span className="block text-xl font-mono font-bold text-white">96.01%</span>
                  <span className="text-[9px] uppercase tracking-wider text-zinc-500 font-bold">RTP Verified</span>
                </div>
                <div className="border-x border-zinc-800/80">
                  <span className="block text-xl font-mono font-bold text-gold-glow">Medium</span>
                  <span className="text-[9px] uppercase tracking-wider text-zinc-500 font-bold">Volatility</span>
                </div>
                <div>
                  <span className="block text-xl font-mono font-bold text-white">25 Fixed</span>
                  <span className="text-[9px] uppercase tracking-wider text-zinc-500 font-bold">Win Lines</span>
                </div>
              </motion.div>

            </div>

            {/* Down arrow anchor */}
            <div className="absolute bottom-6 left-1/2 -translate-x-1/2 z-10 hidden md:block">
              <button 
                onClick={() => scrollToSection('section-bonuses')}
                className="text-gray-500 hover:text-emerald-400 transition-colors duration-200 animate-bounce cursor-pointer"
              >
                <ChevronRight className="w-6 h-6 rotate-90" />
              </button>
            </div>
          </header>

          {/* ====================================================================
             🎁 CASINO PARTNER BONUSES SECTION
             ==================================================================== */}
          <section id="section-bonuses" className="bg-black py-20 px-4 md:px-6 relative border-t border-zinc-900">
            <div className="max-w-7xl mx-auto">
              
              <div className="text-center max-w-xl mx-auto mb-14">
                <span className="text-[10px] uppercase font-mono px-3 py-1 bg-yellow-500/10 border border-yellow-500/20 text-yellow-500 rounded-full font-black tracking-widest">
                  Featured Partner Bonuses
                </span>
                <h2 className="text-3xl md:text-5xl font-serif font-black tracking-wide text-white mt-4 uppercase">
                  EXCLUSIVE PROMOTIONS
                </h2>
                <div className="h-1 w-20 bg-emerald-500 mx-auto mt-4 rounded"></div>
                <p className="text-zinc-500 text-xs md:text-sm mt-4">
                  Boost your starting stake and lock down immediate free spins. These certified virtual casinos guarantee the highest match limits and instant payline support.
                </p>
              </div>

              <BonusOffers />

            </div>
          </section>

          {/* ====================================================================
             🎰 WOLF TREASURE GAME OVERVIEW SECTION (Gauges and Screenshot)
             ==================================================================== */}
          <section id="section-overview" className="bg-zinc-950 py-20 px-4 md:px-6 relative border-y border-zinc-900">
            <div className="max-w-7xl mx-auto">
              
              <div className="flex flex-col lg:flex-row items-center gap-12 lg:gap-16">
                
                {/* Visual Screenshot of Slot Machine (Asset 3 with ornate border) */}
                <div className="w-full lg:w-1/2 relative">
                  <div className="absolute -inset-1.5 bg-gradient-to-tr from-yellow-500 via-transparent to-emerald-500 rounded-2xl blur-md opacity-30"></div>
                  
                  <div className="relative p-2.5 bg-zinc-900 border-4 border-amber-600/70 rounded-2xl shadow-[0_0_35px_rgba(0,0,0,0.8)] overflow-hidden group">
                    <img 
                      src={slotScreenPreview} 
                      alt="Wolf Treasure Pokie Screenshot" 
                      referrerPolicy="no-referrer"
                      className="w-full rounded-lg transition-transform duration-700 group-hover:scale-102"
                    />
                    <div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black via-black/40 to-transparent p-4 text-center">
                      <span className="text-xs uppercase font-mono tracking-widest text-white tracking-widest font-extrabold text-shadow-glow">
                        ⭐️ Authentic IGTech Pokie Grid Preview ⭐️
                      </span>
                    </div>
                  </div>
                </div>

                {/* Structured Text readouts */}
                <div className="w-full lg:w-1/2 space-y-6">
                  <span className="text-[10px] uppercase font-mono px-3 py-1 bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 rounded-full font-black tracking-widest inline-block">
                    Specifications & Blueprint
                  </span>
                  <h2 className="text-3xl md:text-4xl font-serif font-black tracking-wide text-white uppercase text-shadow">
                    GAME OVERVIEW STATS
                  </h2>
                  <p className="text-gray-400 leading-relaxed text-sm md:text-base">
                    Wolf Treasure Pokie delivers a balanced mathematical architecture that caters to casual slot players and high rollers alike. The standard five-reel layout delivers fixed payout configurations backed by high-tier mobile scaling capability.
                  </p>

                  <div className="h-px bg-zinc-800 my-4" />

                  {/* Highlights Grid */}
                  <div className="grid grid-cols-2 gap-4">
                    <div className="p-3.5 bg-zinc-900/60 rounded-xl border border-zinc-800">
                      <span className="text-[10px] text-zinc-500 font-mono font-bold uppercase">Grid Layout</span>
                      <span className="block font-bold text-white text-base">5 reels x 3 rows</span>
                    </div>
                    <div className="p-3.5 bg-zinc-900/60 rounded-xl border border-zinc-800">
                      <span className="text-[10px] text-zinc-500 font-mono font-bold uppercase">Volatility</span>
                      <span className="block font-bold text-white text-base">Balanced (Medium)</span>
                    </div>
                    <div className="p-3.5 bg-zinc-900/60 rounded-xl border border-zinc-800">
                      <span className="text-[10px] text-zinc-500 font-mono font-bold uppercase">Provider</span>
                      <span className="block font-bold text-white text-base">IGTech Systems</span>
                    </div>
                    <div className="p-3.5 bg-zinc-900/60 rounded-xl border border-zinc-800">
                      <span className="text-[10px] text-zinc-500 font-mono font-bold uppercase">Jackpots</span>
                      <span className="block font-bold text-yellow-400 text-base">Mini, Major, Mega</span>
                    </div>
                  </div>
                </div>

              </div>

              {/* Complete Infographic subgrid */}
              <div className="mt-16 pt-8 border-t border-zinc-900">
                <GameOverview />
              </div>

            </div>
          </section>

          {/* ====================================================================
             🎰 POKIE CORES: FEATURES SECTION (Scroll Blocks)
             ==================================================================== */}
          <section id="section-features" className="bg-black py-20 px-4 md:px-6 relative">
            <div className="max-w-7xl mx-auto">
              
              <div className="text-center max-w-xl mx-auto mb-16">
                <span className="text-[10px] uppercase font-mono px-3 py-1 bg-yellow-500/10 border border-yellow-500/20 text-yellow-500 rounded-full font-black tracking-widest">
                  Bonus Mechanism Explained
                </span>
                <h2 className="text-3xl md:text-5xl font-serif font-black tracking-wide text-white mt-4 uppercase">
                  POKIE BONUS FEATURES
                </h2>
                <div className="h-1 w-20 bg-emerald-500 mx-auto mt-3 rounded"></div>
                <p className="text-zinc-500 text-xs md:text-sm mt-4">
                  Learn how the Free Spins and the Hold & Win respin layouts alter standard payline math to offer increased winning potential.
                </p>
              </div>

              <Features />

            </div>
          </section>

          {/* ====================================================================
             💰 PAYTABLE MULTIPLIERS SECTION
             ==================================================================== */}
          <section id="section-paytable" className="bg-zinc-950 py-20 px-4 md:px-6 border-y border-zinc-900 relative">
            <div className="max-w-7xl mx-auto">
              
              <div className="text-center max-w-xl mx-auto mb-14">
                <span className="text-[10px] uppercase font-mono px-3 py-1 bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 rounded-full font-black tracking-widest">
                  Calculated payout symbols
                </span>
                <h2 className="text-3xl md:text-4xl font-serif font-black tracking-wide text-white mt-4 uppercase">
                  SYMBOL MUTUAL PAYTABLE
                </h2>
                <div className="h-1 w-20 bg-emerald-500 mx-auto mt-3 rounded"></div>
                <p className="text-zinc-500 text-xs md:text-sm mt-4">
                  Check item values and matching payout configurations based on standard $1.00 base spin bets. Higher high-value animals award premium multi-cash multipliers!
                </p>
              </div>

              <Paytable />

            </div>
          </section>

          {/* ====================================================================
             📊 PROGRESSIVE HOW TO PLAY STEPS SECTION
             ==================================================================== */}
          <section id="section-gameplay" className="bg-black py-20 px-4 md:px-6 relative">
            <div className="max-w-7xl mx-auto">
              
              <div className="text-center max-w-xl mx-auto mb-14">
                <span className="text-[10px] uppercase font-mono px-3 py-1 bg-yellow-500/10 border border-yellow-500/20 text-yellow-500 rounded-full font-black tracking-widest">
                  Step-by-step game loop
                </span>
                <h2 className="text-3xl md:text-4xl font-serif font-black tracking-wide text-white mt-4 uppercase">
                  HOW TO PLAY ONLINE
                </h2>
                <div className="h-1 w-20 bg-emerald-500 mx-auto mt-3 rounded"></div>
                <p className="text-zinc-500 text-xs md:text-sm mt-4">
                  Follow this quick structured guide to customize your virtual betting configurations and start checking paylines on Wolf Treasure Pokie.
                </p>
              </div>

              <GameplayGuide />

            </div>
          </section>

          {/* ====================================================================
             🎮 MAIN INTERACTIVE PLAYGROUND: DEMO vs REAL SECTION
             ==================================================================== */}
          <section id="section-emulator" className="bg-zinc-950 py-20 px-4 md:px-6 border-y border-zinc-900 relative">
            <div className="absolute inset-0 bg-[radial-gradient(#1e1e1e_1px,transparent_1px)] [background-size:16px_16px] opacity-10 pointer-events-none"></div>

            <div className="max-w-7xl mx-auto">
              
              <div className="text-center max-w-xl mx-auto mb-12">
                <span className="text-[10px] uppercase font-mono px-3 py-1 bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 rounded-full font-black tracking-widest">
                  Select your active play mode
                </span>
                <h2 className="text-3xl md:text-5xl font-serif font-black tracking-wide text-white mt-4 uppercase">
                  DEMO vs REAL MONEY MODE
                </h2>
                <div className="h-1 w-20 bg-emerald-500 mx-auto mt-3 rounded"></div>
                <p className="text-zinc-500 text-xs md:text-sm mt-4">
                  Toggle modes below. Work on your spins in our fully loaded interactive slot emulator, or proceed directly to cash layouts on certified casino servers.
                </p>
              </div>

              {/* Mode Toggle Animation tab */}
              <div className="flex justify-center mb-10">
                <div className="p-1 rounded-2xl bg-black border border-zinc-800 flex gap-2">
                  <button
                    onClick={() => setMode('demo')}
                    className={`px-6 py-3 rounded-xl text-xs uppercase tracking-widest font-extrabold transition-all duration-300 cursor-pointer ${
                      mode === 'demo'
                        ? 'bg-gradient-to-r from-emerald-500 to-green-600 text-black shadow-[0_0_12px_rgba(16,185,129,0.3)]'
                        : 'text-gray-400 hover:text-white'
                    }`}
                  >
                    🎮 Play Simulated Demo
                  </button>
                  <button
                    onClick={() => setMode('real')}
                    className={`px-6 py-3 rounded-xl text-xs uppercase tracking-widest font-extrabold transition-all duration-300 cursor-pointer ${
                      mode === 'real'
                        ? 'bg-gradient-to-r from-yellow-500 to-amber-600 text-black shadow-[0_0_12px_rgba(245,158,11,0.3)]'
                        : 'text-gray-400 hover:text-white'
                    }`}
                  >
                    🔥 Get Real Money Bonuses
                  </button>
                </div>
              </div>

              {/* Conditional Mode Renderer with staggered animations */}
              <AnimatePresence mode="wait">
                {mode === 'demo' ? (
                  <motion.div
                    key="demo-play-card"
                    initial={{ opacity: 0, scale: 0.96 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.96 }}
                    transition={{ duration: 0.35 }}
                    id="playable-demo-block"
                  >
                    <SlotEmulator />
                  </motion.div>
                ) : (
                  <motion.div
                    key="real-play-card"
                    initial={{ opacity: 0, scale: 0.96 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.96 }}
                    transition={{ duration: 0.35 }}
                    className="max-w-4xl mx-auto rounded-3xl border-2 border-yellow-500/40 bg-zinc-950 p-8 md:p-12 text-center shadow-[0_0_40px_rgba(234,179,8,0.15)] relative overflow-hidden"
                    id="real-payouts-block"
                  >
                    {/* Background decoration */}
                    <div className="absolute -right-16 -top-16 w-48 h-48 bg-yellow-500/5 rounded-full blur-2xl"></div>
                    <div className="absolute -left-16 -bottom-16 w-48 h-48 bg-purple-500/5 rounded-full blur-2xl"></div>

                    <div className="relative z-10 flex flex-col items-center">
                      <div className="p-3 bg-yellow-500/15 border border-yellow-500/30 text-yellow-400 rounded-full mb-6 shadow-inner">
                        <Flame className="w-8 h-8 text-yellow-400 animate-pulse" />
                      </div>

                      <h3 className="text-2xl md:text-4xl font-serif font-black tracking-wide text-white uppercase leading-tight">
                        WANT TO TRIGGER <span className="text-gold-glow">REAL</span> MULTIPLIERS?
                      </h3>
                      <p className="text-gray-300 max-w-2xl text-xs md:text-sm mt-5 leading-relaxed">
                        Transitioning to Real Money lets you withdraw your wins directly back to your secure on-chain wallet or bank. Cash out in under 15 minutes while claiming match bonuses from Zoome, Zota, and Cusco casinos!
                      </p>

                      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 w-full max-w-2xl mt-10">
                        <div className="p-5 bg-black/60 rounded-2xl border border-zinc-850 text-left flex items-start gap-3">
                          <CheckCircle className="w-5 h-5 text-emerald-400 shrink-0 mt-0.5" />
                          <div>
                            <span className="block text-xs font-bold text-white uppercase font-sans">Full Cash Withdraw</span>
                            <p className="text-[11px] text-zinc-500 leading-normal mt-1">Direct wire to PayID, Cards, and Coins without hidden commissions.</p>
                          </div>
                        </div>

                        <div className="p-5 bg-black/60 rounded-2xl border border-zinc-850 text-left flex items-start gap-3">
                          <CheckCircle className="w-5 h-5 text-emerald-400 shrink-0 mt-0.5" />
                          <div>
                            <span className="block text-xs font-bold text-white uppercase font-sans">Immediate Syncing</span>
                            <p className="text-[11px] text-zinc-500 leading-normal mt-1">Get automatically listed for VIP rebates and exclusive free spin drops.</p>
                          </div>
                        </div>

                        <div className="p-5 bg-black/60 rounded-2xl border border-zinc-850 text-left flex items-start gap-3">
                          <CheckCircle className="w-5 h-5 text-emerald-400 shrink-0 mt-0.5" />
                          <div>
                            <span className="block text-xs font-bold text-white uppercase font-sans">96.01% Standard RTP</span>
                            <p className="text-[11px] text-zinc-500 leading-normal mt-1">Certified RNG and volatility ratings identical to real slot cabinets.</p>
                          </div>
                        </div>
                      </div>

                      <div className="mt-10 flex flex-col items-center gap-4">
                        <button
                          onClick={playNow}
                          className="px-10 py-4 bg-gradient-to-r from-yellow-500 to-amber-600 hover:from-yellow-400 hover:to-amber-500 text-black font-black uppercase tracking-widest text-sm rounded-full transition-all duration-300 shadow-[0_0_20px_#eab308] hover:shadow-[0_0_35px_#f59e0b] hover:scale-105 cursor-pointer flex items-center gap-2"
                        >
                          <Play className="w-4 h-4 fill-black text-black" />
                          Register & Play For Real Now
                        </button>
                        <span className="text-[10px] uppercase font-mono text-zinc-500">
                          Requires 18+ verification | Please play responsibly
                        </span>
                      </div>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>

            </div>
          </section>

          {/* ====================================================================
             💳 SUPPORTED SECURE PAYMENT SYSTEMS SECTION
             ==================================================================== */}
          <section id="section-payments" className="bg-black py-20 px-4 md:px-6 relative">
            <div className="max-w-7xl mx-auto">
              
              <div className="text-center max-w-xl mx-auto mb-14">
                <span className="text-[10px] uppercase font-mono px-3 py-1 bg-yellow-500/10 border border-yellow-500/20 text-yellow-500 rounded-full font-black tracking-widest">
                  Secure Deposits & Withdrawals
                </span>
                <h2 className="text-3xl md:text-4xl font-serif font-black tracking-wide text-white mt-4 uppercase">
                  SUPPORTED BANK CHANNELS
                </h2>
                <div className="h-1 w-20 bg-emerald-500 mx-auto mt-3 rounded"></div>
                <p className="text-zinc-500 text-xs md:text-sm mt-4">
                  Enjoy instantaneous payouts with full encryption across both standard wire nets and digital crypto vectors.
                </p>
              </div>

              <PaymentSlider />

            </div>
          </section>

          {/* ====================================================================
             ❓ HELP ACCORDIONS FAQ SECTION
             ==================================================================== */}
          <section id="section-faq" className="bg-zinc-950 py-20 px-4 md:px-6 relative border-t border-zinc-900">
            <div className="max-w-7xl mx-auto">
              
              <div className="text-center max-w-sm mx-auto mb-14">
                <span className="text-[10px] uppercase font-mono px-3 py-1 bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 rounded-full font-black tracking-widest">
                  Help Desk & Regulatory Answers
                </span>
                <h2 className="text-3xl md:text-4xl font-serif font-black tracking-wide text-white mt-4 uppercase">
                  FREQUENT QUESTIONS
                </h2>
                <div className="h-1 w-16 bg-emerald-500 mx-auto mt-3 rounded"></div>
              </div>

              <FAQ />

            </div>
          </section>

          {/* ====================================================================
             🛡️ COMPLIANCE WARNING & BRAND FOOTER RAIL
             ==================================================================== */}
          <footer className="bg-black border-t border-zinc-900 py-12 px-4 md:px-6 relative z-15 text-center">
            <div className="max-w-7xl mx-auto">
              
              <div className="flex justify-center items-center gap-2 text-2xl animate-pulse mb-4">
                <span>🐺</span>
                <span className="font-serif font-black text-white uppercase tracking-wider">WOLF TREASURE POKIE</span>
              </div>

              <p className="text-xs text-zinc-500 leading-relaxed max-w-2xl mx-auto">
                Wolf Treasure Pokie is an independent review, walkthrough, and instructional resource created for video slot fans. All trademarks are held by IGTech Systems. Simulated games utilize free theoretical balance models with no actual economic hazard or deposit requirements.
              </p>

              {/* Responsible betting citation badges */}
              <div className="flex flex-wrap items-center justify-center gap-4 md:gap-6 mt-8 font-mono text-[10px] text-zinc-400 uppercase">
                <span className="px-3 py-1.5 bg-zinc-950 rounded-lg border border-zinc-900">🔞 18+ Responsible Gaming Only</span>
                <span className="px-3 py-1.5 bg-zinc-950 rounded-lg border border-zinc-900">🔒 SSL Encrypted Syncing</span>
                <span className="px-3 py-1.5 bg-zinc-950 rounded-lg border border-zinc-900">🎯 RNG Systems Audited</span>
                <span className="px-3 py-1.5 bg-zinc-950 rounded-lg border border-zinc-900">⚡ BeGambleAware Certified</span>
              </div>

              <div className="h-px bg-zinc-900/60 my-8 max-w-3xl mx-auto" />

              <div className="flex flex-col md:flex-row justify-between items-center text-[10px] text-zinc-600 gap-4 font-mono">
                <p>© 2026 Wolf Treasure Pokie. Built in Cloud Gaming Workspaces. All rights reserved.</p>
                <div className="flex gap-4">
                  <a href={REDIRECT_URL} target="_blank" rel="noopener noreferrer" className="hover:text-emerald-400 transition-colors uppercase">Affiliate Terms</a>
                  <span>|</span>
                  <a href={REDIRECT_URL} target="_blank" rel="noopener noreferrer" className="hover:text-emerald-400 transition-colors uppercase">Privacy Guidelines</a>
                  <span>|</span>
                  <a href={REDIRECT_URL} target="_blank" rel="noopener noreferrer" className="hover:text-emerald-400 transition-colors uppercase">Support Ledger</a>
                </div>
              </div>

            </div>
          </footer>

        </motion.div>
      )}

    </div>
  );
}
